name: Monthly Site Rebuild

on:
  schedule:
    - cron: '0 0 1 * *' # Triggers at 00:00 on the 1st day every month
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Updated to a more recent version
          bundler-cache: true # Caches bundle install

      - name: Build the site with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Commit changes
        run: |
          git config --global user.email "pg.prob.sem@gmail.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Monthly rebuild of site" -a || echo "No changes to commit"
          git push
