name: Monthly Site Rebuild

on:
    schedule:
        - cron: "1 0 * * *" # Triggers daily
    workflow_dispatch: # Allows manual triggering

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.0"
                  bundler-cache: true

            - name: Build the site with Jekyll
              run: bundle exec jekyll build
              env:
                  JEKYLL_ENV: production
                  PAGES_REPO_NWO: ${{ github.repository }}

            - name: Commit changes
              run: |
                  git config --global user.email "pg.prob.sem@gmail.com"
                  git config --global user.name "GitHub Actions"
                  git add -A
                  git commit -m "Monthly rebuild of site" -a || echo "No changes to commit"
                  git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
